{% set version = "3.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-maps
  version: {{ version|replace("-", "_") }}

source:
  fn: maps_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/maps_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/maps/maps_{{ version }}.tar.gz
  sha256: 7918ccb2393ca19589d4c4e77d9ebe863dc6317ebfc1ff41869dbfaf439f5747

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('maps')"           # [not win]
    - "\"%R%\" -e \"library('maps')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=maps
  license: GPL-2
  summary: Display of maps.  Projection code and larger maps are in separate packages ('mapproj' and 'mapdata').
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
