travis:
  secure:
    BINSTAR_TOKEN: SeGo5VDl8O7U7ejtnN/HzEaDPphNW2+9w5VIf/UBnj7krZlEt4/3/+G9DmqU7Hdf3oqtv3BXArjo8SSmQYGwwMm027x+4ppwRKwE777LFD4Z8B7SOpfPqHu3KZQPbD3lpKRwxSzTKJ9VtFkMDTxmIv0wuhmOEl3RSfxx8dIMZJMqc3jVyamgR3gwcJ0YubU2DZNYZ5gC6itVIy6bGIv6lZVWLvwcqBF6LWSwmlliA+9/yMYcAUvcVMvm5HnStinXSN0HpbgTdHUwZupPmPgHN6yX3jr3wuILWFN50xiEyOaz9DosQ77duX0fXsKTCaADTpwv8yQYeEMbYnfpe1orahg474qgdgddGOBB99irh/QCQXzLsLYfQI3GxKDwt3rQi/DNJWiUcSBi2ZomtXL2pLTkHDEAxcWUvbUVy5eYLfBA8luYKwnN/1vSk9XerT2agdoYeA8f0mOz0BcfP03uo/Pjzby0MHYX3YzeFyPV69raH+G2vSYnuLUmQ9I+f0sYunvOpo8zhI8YveuI4PZh7yVZkdjvKUG2OK0D2VCojyPOWgo6Oseh6rP+A+IpsRCku5lt1QkS/fE5bPPq1EG72IbTm6ZkuJXXgoXYOjthyz+4/HGKJuQnfMr28oD8xIjzte4mu+UU1CGzChQOovbZ30VHYeEl5mcUcqf2KTufS/s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
